# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsStatsForm.ui'
#
# Created: Fri Apr 19 14:08:24 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qgsStatsForm(object):
    def setupUi(self, qgsStatsForm):
        qgsStatsForm.setObjectName(_fromUtf8("qgsStatsForm"))
        qgsStatsForm.resize(468, 600)
        qgsStatsForm.setMinimumSize(QtCore.QSize(468, 343))
        qgsStatsForm.setMaximumSize(QtCore.QSize(468, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qgsStatsForm.setWindowIcon(icon)
        qgsStatsForm.setModal(True)
        self.gridLayout_6 = QtGui.QGridLayout(qgsStatsForm)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox = QtGui.QGroupBox(qgsStatsForm)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtCurrentVectorLayer = QtGui.QLineEdit(self.groupBox)
        self.txtCurrentVectorLayer.setObjectName(_fromUtf8("txtCurrentVectorLayer"))
        self.gridLayout.addWidget(self.txtCurrentVectorLayer, 1, 1, 2, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.cboFields = QtGui.QComboBox(self.groupBox)
        self.cboFields.setObjectName(_fromUtf8("cboFields"))
        self.gridLayout.addWidget(self.cboFields, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(qgsStatsForm)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtPathDirRasters = QtGui.QLineEdit(self.groupBox_2)
        self.txtPathDirRasters.setText(_fromUtf8(""))
        self.txtPathDirRasters.setObjectName(_fromUtf8("txtPathDirRasters"))
        self.gridLayout_2.addWidget(self.txtPathDirRasters, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.btnRasterDir = QtGui.QPushButton(self.groupBox_2)
        self.btnRasterDir.setObjectName(_fromUtf8("btnRasterDir"))
        self.gridLayout_2.addWidget(self.btnRasterDir, 2, 3, 1, 1)
        self.txtNoData = QtGui.QLineEdit(self.groupBox_2)
        self.txtNoData.setMaximumSize(QtCore.QSize(60, 16777215))
        self.txtNoData.setObjectName(_fromUtf8("txtNoData"))
        self.gridLayout_2.addWidget(self.txtNoData, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(qgsStatsForm)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnGDALPath = QtGui.QPushButton(self.groupBox_5)
        self.btnGDALPath.setObjectName(_fromUtf8("btnGDALPath"))
        self.gridLayout_3.addWidget(self.btnGDALPath, 0, 1, 1, 1)
        self.txtGDALPath = QtGui.QLineEdit(self.groupBox_5)
        self.txtGDALPath.setObjectName(_fromUtf8("txtGDALPath"))
        self.gridLayout_3.addWidget(self.txtGDALPath, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 3, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(qgsStatsForm)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.txtOutputFileResult = QtGui.QLineEdit(self.groupBox_3)
        self.txtOutputFileResult.setObjectName(_fromUtf8("txtOutputFileResult"))
        self.gridLayout_5.addWidget(self.txtOutputFileResult, 0, 1, 1, 1)
        self.btnOutFileResult = QtGui.QPushButton(self.groupBox_3)
        self.btnOutFileResult.setObjectName(_fromUtf8("btnOutFileResult"))
        self.gridLayout_5.addWidget(self.btnOutFileResult, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(qgsStatsForm)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnStart = QtGui.QPushButton(self.groupBox_4)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.gridLayout_4.addWidget(self.btnStart, 1, 1, 1, 1)
        self.btnClose = QtGui.QPushButton(self.groupBox_4)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout_4.addWidget(self.btnClose, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 5, 0, 1, 2)
        self.lstLogs = QtGui.QListWidget(qgsStatsForm)
        self.lstLogs.setObjectName(_fromUtf8("lstLogs"))
        self.gridLayout_6.addWidget(self.lstLogs, 4, 0, 1, 1)

        self.retranslateUi(qgsStatsForm)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL(_fromUtf8("clicked()")), qgsStatsForm.close)
        QtCore.QMetaObject.connectSlotsByName(qgsStatsForm)

    def retranslateUi(self, qgsStatsForm):
        qgsStatsForm.setWindowTitle(QtGui.QApplication.translate("qgsStatsForm", "Raster Stats by Features", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("qgsStatsForm", "Vector Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qgsStatsForm", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("qgsStatsForm", "Raster Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.txtPathDirRasters.setToolTip(QtGui.QApplication.translate("qgsStatsForm", "<html><head/><body><p align=\"justify\">Select a directory where you store the images.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("qgsStatsForm", "NoData", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("qgsStatsForm", "Raster Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRasterDir.setText(QtGui.QApplication.translate("qgsStatsForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("qgsStatsForm", "GDAL Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGDALPath.setText(QtGui.QApplication.translate("qgsStatsForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.txtGDALPath.setToolTip(QtGui.QApplication.translate("qgsStatsForm", "<html><head/><body><p>Input the full path to name file output. Here we store all results of calcs in a text file with delimiter (csv)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("qgsStatsForm", "Results Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("qgsStatsForm", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.txtOutputFileResult.setToolTip(QtGui.QApplication.translate("qgsStatsForm", "<html><head/><body><p>Input the full path to name file output. Here we store all results of calcs in a text file with delimiter (csv)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutFileResult.setText(QtGui.QApplication.translate("qgsStatsForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStart.setText(QtGui.QApplication.translate("qgsStatsForm", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("qgsStatsForm", "Close", None, QtGui.QApplication.UnicodeUTF8))

import resource
